apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: NODE_APP_IMAGE_NAME
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
